Grid and Form Permissions
manojpandeyDev18/dframework-ui pull request #2
Opened 2024-11-19 07:43 UTC by samargupta007

2024-11-20 15:12 UTC, Pramodspraxa requested changes

2024-11-20 15:12 UTC, Pramodspraxa commented on src/lib/components/utils.js
> +export const getPermissions = (userData, model, fallbackPermissions = {}) => {
Code should be like below - 

```
export const getPermissions = (userData, model, fallbackPermissions = {}) => {
    const userPermissions = userData?.filter(item => item.Module === model.module) || [];
    const permissionsToUse = userPermissions.length ? userPermissions[0] : {};
    if(!userPermissions.length) {
	return { canAdd: fallbackPermissions.add || false, canEdit: fallbackPermissions.edit || false, canDelete: fallbackPermissions.delete || false };
    }
    return {
        canAdd: permissionsToUse.Permission2 === 1,
        canEdit: permissionsToUse.Permission3 === 1,
        canDelete: permissionsToUse.Permission4 === 1 
    };
};
```

2024-11-20 15:12 UTC, Pramodspraxa commented on src/lib/components/Form/Form.js
> +    const fallbackPermissions = {edit: permissions.edit,delete: permissions.delete};
add permission is misssing. 
If someone start to use directly then it by default will come as false always.

2024-11-20 15:12 UTC, Pramodspraxa commented on src/lib/components/Grid/index.js
> +    const fallbackPermissions = {add: effectivePermissions.add,edit: effectivePermissions.edit,delete: effectivePermissions.delete};
formatting missing.

2024-11-20 15:12 UTC, Pramodspraxa commented on src/lib/components/Grid/index.js
> +    const fallbackPermissions = {add: effectivePermissions.add,edit: effectivePermissions.edit,delete: effectivePermissions.delete};
fallbackPermissions
name should be userDefinePermissions or something.

2024-11-20 15:12 UTC, Pramodspraxa commented on src/lib/components/Grid/index.js
> +                {(isReadOnly || (!canAdd && !forAssignment)) && <Typography variant="h6" component="h3" textAlign="center" sx={{ ml: 1 }} > {isReadOnly ? "" : canAdd ? model.title : ''}</Typography>}
this extra condition should never occur - 
: canAdd ? model.title : ''

2024-11-21 06:40 UTC, manojpandeyDev18 approved these changes

2024-11-21 06:40 UTC, merged