55739 common config and child grid
manojpandeyDev18/dframework-ui pull request #8
Opened 2024-11-25 14:04 UTC by SuyashSingh15

2024-11-25 14:42 UTC, manojpandeyDev18 requested changes

2024-11-26 06:15 UTC, SuyashSingh15 commented on src/lib/components/Grid/index.js
> +            console.log('3');
removed

2024-11-26 06:17 UTC, SuyashSingh15 commented on src/lib/components/Grid/index.js
> +        if (props.isChildGrid) {
done

2024-11-26 06:17 UTC, SuyashSingh15 commented on src/lib/components/Grid/index.js
> +            console.log('6');
rf logs

2024-11-28 06:05 UTC, merged